version: '2'
services:
    managementportal-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=radarcns
            - POSTGRES_PASSWORD=radarcns
            - POSTGRES_DB=managementportal
